image: alpine:latest

variables:
  REPO_NAME: gitlab.com/diamondburned/6cord

before_script:
  - apk add upx go git
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - build

compile:
    stage: build
    script:
      - time go get
      # compiles 6cord without cgo so that it's statically linked 
      # may affect performance
      - time CGO_ENABLED=0 go build -ldflags "-w -extldflags '-static'" -o $CI_PROJECT_DIR/6cord
      - strip $CI_PROJECT_DIR/6cord
      - upx $CI_PROJECT_DIR/6cord
      - time GOOS=windows go get
      - time GOOS=windows CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/6cord.exe
    artifacts:
      paths:
        - 6cord
        - 6cord.exe
