image: golang:alpine

variables:
  REPO_NAME: gitlab.com/diamondburned/6cord

before_script:
  - apk add upx git
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - build

compile:
    stage: build
    script:
      - time go get -d -f u -v
      # compiles 6cord without cgo so that it's statically linked 
      # may affect performance
      - export CG_ENABLED=0
      - time go build -ldflags "-s -extldflags '-static'" -o $CI_PROJECT_DIR/6cord
      - upx $CI_PROJECT_DIR/6cord
      - export GOOS=windows
      - time go get -d -f -u -v
      - time go build -o $CI_PROJECT_DIR/6cord.exe
    artifacts:
      paths:
        - 6cord
        - 6cord.exe
