image: golang:alpine

variables:
  GO111MODULE: "on"
  CGO_ENABLED: 0

before_script:
  - apk add git upx

stages:
    - build

linux:
    stage: build
    script:
      - time go get
      - export FLAGS="-ldflags -w -ldflags -s"
      # compiles 6cord without cgo so that it's statically linked 
      # may affect performance - disabled for ueberzug + xorg
      - time go build $FLAGS -o $CI_PROJECT_DIR/6cord
      - upx -q --8086 -9 $CI_PROJECT_DIR/6cord
      - time go build $FLAGS -o $CI_PROJECT_DIR/6cord_nk -tags nokeyring
      - upx -q --8086 -9 $CI_PROJECT_DIR/6cord_nk
    artifacts:
      paths:
        - 6cord
        - 6cord_nk

linux_arm64:
  stage: build
  script:
    - export GOOS=linux GOARCH=arm64
    - time go get
    - time go build -o $CI_PROJECT_DIR/6cord_arm64
  artifacts:
    paths:
      - 6cord_arm64

windows:
  stage: build
  script:
    - export GOOS=windows
    - time go get 
    - time go build -o $CI_PROJECT_DIR/6cord.exe
  artifacts:
    paths:
      - 6cord.exe

